CREATE TABLE `group_chat_auto_join_backup_staff` (
  `id` bigint NOT NULL COMMENT 'ID',
  `ext_corp_id` char(18) COMMENT '外部企业ID',
  `ext_creator_id` char(64) COMMENT '创建者外部员工ID',
  `group_chat_auto_join_code_id` bigint COMMENT '自动拉群码id',
  `daily_add_customer_count` bigint DEFAULT 0 COMMENT '员工每日添加客户计数',
  `add_customer_count` bigint DEFAULT 0 COMMENT '员工累计添加客户计数',
  `daily_add_customer_limit` bigint COMMENT '员工每日添加客户上限',
  `avatar` longtext COMMENT '员工头像',
  `staff_id` bigint COMMENT '员工ID',
  `ext_staff_id` varchar(191) COMMENT '外部员工ID',
  `name` longtext COMMENT '员工名称',
  `created_at` datetime(3) COMMENT '创建时间',
  `updated_at` datetime(3) COMMENT '更新时间',
  `deleted_at` datetime(3) COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `idx_ext_corp_id` (`ext_corp_id`),
  KEY `idx_ext_creator_id` (`ext_creator_id`),
  KEY `idx_auto_join_code_staff` (`group_chat_auto_join_code_id`, `staff_id`),
  KEY `idx_ext_staff_id` (`ext_staff_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_updated_at` (`updated_at`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='自动拉群码绑定的备份员工';
